"""Initial migration

Revision ID: 177f0cc03e0b
Revises: 
Create Date: 2025-03-20 19:43:36.680699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177f0cc03e0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coords_id'), 'coords', ['id'], unique=False)
    op.create_table('levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('winter', sa.String(length=2), nullable=True),
    sa.Column('summer', sa.String(length=2), nullable=True),
    sa.Column('autumn', sa.String(length=2), nullable=True),
    sa.Column('spring', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('fam', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('otc', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('perevaladdeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beauty_title', sa.String(length=250), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('other_titles', sa.String(length=250), nullable=False),
    sa.Column('connect', sa.Text(), nullable=True),
    sa.Column('add_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coord_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'pending', 'accepted', 'rejected', name='statusenum'), nullable=False),
    sa.ForeignKeyConstraint(['coord_id'], ['coords.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perevaladdeds_id'), 'perevaladdeds', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('pereval_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pereval_id'], ['perevaladdeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_perevaladdeds_id'), table_name='perevaladdeds')
    op.drop_table('perevaladdeds')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_coords_id'), table_name='coords')
    op.drop_table('coords')
    # ### end Alembic commands ###
