name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with ruff
      run: |
        ruff format src/
        ruff check src/
    - name: Run tests
      env:
        FSTR_DB_HOST: ${{ secrets.FSTR_DB_HOST }}
        FSTR_DB_PORT: ${{ secrets.FSTR_DB_PORT }}
        FSTR_DB_NAME: ${{ secrets.FSTR_DB_NAME }}
        FSTR_DB_LOGIN: ${{ secrets.FSTR_DB_LOGIN }}
        FSTR_DB_PASS: ${{ secrets.FSTR_DB_PASS }}
      run: |
        pytest