on:
  push:
    branches:
      - 'docker_files'

jobs:
  build_image_to_yc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Yandex Cloud
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: ${{secrets.YANDEX_REGISTRY_ID}}
          CR_REPOSITORY: ${{secrets.YANDEX_REPO_NAME}}
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

  deploy_image_to_yc:
    needs: build_image_to_yc
    runs-on: ubuntu-latest
    steps:
      - name: Connect to VM on SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.YANDEX_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.YANDEX_SSH_PASSPHRASE }}
          port: ${{ secrets.VM_PORT }}
      - name: Rum commands to VM
          env:
            CR_REGISTRY: ${{ secrets.YANDEX_REGISTRY_ID }}
            CR_REPOSITORY: ${{ secrets.YANDEX_REPO_NAME }}
            IMAGE_TAG: ${{ github.sha }}
            OAUTH_DOCKER_PASS: ${{ secrets.OAUTH_DOCKER_PASS }}
          script: |
            sudo docker login --username oauth --pasword $OAUTH_DOCKER_PASS cr.yandex
            sudo docker pull cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
            sudo docker rm -f pereval
            sudo docker run -d -p 8080:8080 --name pereval cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG